name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Install .NET
        uses: actions/setup-dotnet@c7e7147fd3e41056e75a761416c06f5fa781b5fb
        with:
          dotnet-version: "6.0.100"

      - name: Run tests
        run: pwsh ./test.ps1
