name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Install .NET
        uses: actions/setup-dotnet@499789684c9a0d41c9b3f0d66a785ba17b1d51ab
        with:
          dotnet-version: "6.0.100"

      - name: Run tests
        run: pwsh ./test.ps1
